### PR TITLE
Remove internal use of exceptions

### LINKED ISSUE #43: Remove internal use of exceptions
This will enable reporting all deserialization errors instead of just the first one and will make implementing #40 a lot easier.

### PR DESCRIPTION
**Pull request by darioteixeira**
Closes #43

### CODE REVIEW

File: lib/runtime/ppx_mysql_runtime.ml [hunk 1]
```diff
@@ -1,3 +1,57 @@
+type column_error =
+  [ `Expected_non_null_column of int * string
+  | `Deserialization_error of int * string * string * string * string ]
+
+type 'a deserializer = string -> ('a, [`Deserialization_error of string]) result
+
+let wrap_failure of_string s =
```
Comment (Leonidas-from-XIV) [inline lib/runtime/ppx_mysql_runtime.ml]: Wouldn't `f` be more appropriate here? Or maybe a type signature restricting `of_string` to convert?

File: lib/runtime/ppx_mysql_runtime.ml [hunk 2]
```diff
@@ -1,3 +1,57 @@
...
+let int_of_string = wrap_failure Pervasives.int_of_string
+
+let int32_of_string = wrap_failure Int32.of_string
+
+let int64_of_string = wrap_failure Int64.of_string
+
+let bool_of_string str =
+  match Pervasives.int_of_string str with
+  | v ->
+      Ok (v <> 0)
```
Comment (Leonidas-from-XIV) [inline lib/runtime/ppx_mysql_runtime.ml]: I'd try to avoid polymorphic compare here.

File: lib/runtime/ppx_mysql_runtime.ml [hunk 3]
```diff
@@ -1,3 +1,57 @@
...
+  | exception Failure _ ->
+      Error (`Deserialization_error "cannot parse boolean")
+
+let identity v = v
```
Comment (Leonidas-from-XIV) [inline lib/runtime/ppx_mysql_runtime.ml]: Maybe use `%identity` here?

File: lib/runtime/ppx_mysql_runtime.ml (hunk 1 above)
Comment (darioteixeira) [reply lib/runtime/ppx_mysql_runtime.ml]: I've restricted the signature.

File: lib/runtime/ppx_mysql_runtime.ml (hunk 3 above)
Comment (darioteixeira) [reply lib/runtime/ppx_mysql_runtime.ml]: I dunno, feels a bit too hackish and low-level. Moreover, the Brave New Flambda World will soon be upon us... ;-)

File: lib/runtime/ppx_mysql_runtime.ml (hunk 2 above)
Comment (darioteixeira) [reply lib/runtime/ppx_mysql_runtime.ml]: It's not obvious to me the type of comparison that the compiler will use. I would've guessed it uses a specialised integer comparison, because it does have the type information to make that decision.

File: lib/runtime/ppx_mysql_runtime.ml (hunk 3 above)
Comment (darioteixeira) [reply lib/runtime/ppx_mysql_runtime.ml]: The latest commit now uses `%identity`.
